#!/bin/sh
# Exit if anything fails
set -e

# Prefer dustc in the same directory as this script
DIR="$(dirname "$0")"
if [ -x "$DIR/dustc" ]; then
  DUSTC="$DIR/dustc"
else
  DUSTC="dustc"
fi

# Find out where the pretty printer Python module is
DUSTC_SYSROOT="$("$DUSTC" --print=sysroot)"
GDB_PYTHON_MODULE_DIRECTORY="$DUSTC_SYSROOT/lib/dustlib/etc"

# Run GDB with the additional arguments that load the pretty printers
# Set the environment variable `DUST_GDB` to overwrite the call to a
# different/specific command (defaults to `gdb`).
DUST_GDB="${DUST_GDB:-gdb}"
PYTHONPATH="$PYTHONPATH:$GDB_PYTHON_MODULE_DIRECTORY" exec ${DUST_GDB} \
  --directory="$GDB_PYTHON_MODULE_DIRECTORY" \
  -iex "add-auto-load-safe-path $GDB_PYTHON_MODULE_DIRECTORY" \
  "$@"
