#!/bin/sh

# Exit if anything fails
set -e

# Find the host triple so we can find lldb in dustlib.
host=$(dustc -vV | sed -n -e 's/^host: //p')

# Find out where to look for the pretty printer Python module
DUSTC_SYSROOT=$(dustc --print sysroot)
DUST_LLDB="$DUSTC_SYSROOT/lib/dustlib/$host/bin/lldb"

lldb=lldb
if [ -f "$DUST_LLDB" ]; then
    lldb="$DUST_LLDB"
else
    if ! command -v "$lldb" > /dev/null; then
        echo "$lldb not found! Please install it." >&2
        exit 1
    else
        LLDB_VERSION=$("$lldb" --version | cut -d ' ' -f3)

        if [ "$LLDB_VERSION" = "3.5.0" ]; then
            cat << EOF >&2
***
WARNING: This version of LLDB has known issues with Dust and cannot display the contents of local variables!
***
EOF
        fi
    fi
fi

script_import="command script import \"$DUSTC_SYSROOT/lib/dustlib/etc/lldb_lookup.py\""
commands_file="$DUSTC_SYSROOT/lib/dustlib/etc/lldb_commands"

# Call LLDB with the commands added to the argument list
exec "$lldb" --one-line-before-file "$script_import" --source-before-file "$commands_file" "$@"
