LIB := $(shell $(DUSTC) --print file-names --crate-type=lib $(TMPDIR)/lib.rs)

$(TMPDIR)/$(LIB):
	$(DUSTC) --emit link,dep-info --crate-type=lib $(TMPDIR)/lib.rs
	touch $(TMPDIR)/done

-include $(TMPDIR)/lib.d
